require("core.config_plugins.chatgpt")
require("core.config_plugins.fugitive")
require("core.config_plugins.harpoon")
require("core.config_plugins.iron")
require("core.config_plugins.lsp")
require("core.config_plugins.rose-pine")
require("core.config_plugins.telescope")
require("core.config_plugins.treesitter")
require("core.config_plugins.undotree")

