#!/bin/bash

# Define the input and output files
sequences_file="$HOME/.config/wpg/sequences"
xresources_file="$HOME/.Xresources"

# Extract the color sequences
colors=$(grep -oP '(?<=;)[0-9]+;#[0-9a-fA-F]{6}' "$sequences_file")

# Remove existing color definitions from .Xresources file
sed -i '/^! Colors generated by WPG using Pywal/,/^! End generated colors/d' "$xresources_file"

# Write the new color definitions to the .Xresources file
echo "! Colors generated by WPG using Pywal" >> "$xresources_file"
while read -r color; do
    # Split the index and the color code
    index=$(echo "$color" | cut -d ';' -f 1)
    color_code=$(echo "$color" | cut -d ';' -f 2)

    # Write the color definition to the .Xresources file
    echo "*color${index}: ${color_code}" >> "$xresources_file"
done <<< "$colors"
echo "! End generated colors" >> "$xresources_file"

# Load the new color definitions
xrdb -merge "$xresources_file"

echo "Colors have been updated in $xresources_file and loaded."
